package kr.co.kumoh.illdang100.mollyspring.domain.pet;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum CatEnum {

    NORWEGIAN_FOREST("노르웨이 숲"),
    NEBELUNG("네벨룽"),
    NEVA_MASQUERADE("네바 마스커레이드"),
    DEVON_REX("데본렉스"),
    DOMESTIC_SHORTHAIR("도메스틱 숏헤어"),
    DOMESTIC_LONGHAIR("도메스틱 롱헤어"),
    DONSKOI("돈스코이"),
    DON_SPHINX("돈스핑크스"),
    RAGAMUFFIN("라가머핀"),
    RAGDOLL("랙돌"),
    RUSSIAN_BLUE("러시안 블루"),
    LYCOY("라이코이"),
    LAFAM("라팜"),
    MANX("맹크스"),
    MAINE_COON("메인쿤"),
    MUNCHKIN("먼치킨"),
    MINUET("미뉴에트"),
    BALINESE("발리니즈"),
    BERMAN("버만"),
    BURMESE("버미즈"),
    BENGAL("벵갈"),
    BOMBAY("봄베이"),
    BRITISH_SHORTHAIR("브리티시 쇼트헤어"),
    BRITISH_LONGHAIR("브리티시 롱헤어"),
    BURMILLA("버밀라"),
    SIBERIAN("시베리안"),
    SIAMESE("샴"),
    CHARTLUX("샤트룩스"),
    SELKIRK_REX("셀커크 렉스"),
    SOMALI("소말리"),
    SCOTTISH_FOLD("스코티시 폴드"),
    SCOTTISH_STRAIGHT("스코티시 스트레이트"),
    SPHINX("스핑크스"),
    SINGAPURA("싱가푸라"),
    SNOWSHOE("스노우슈"),
    SAVANNAH("사바나"),
    SOKOKE("소코케"),
    ARABIAN_CORMORANT("아라비안 마우"),
    AMERICAN_BOBTAIL("아메리칸 밥테일"),
    AMERICAN_SHORTHAIR("아메리칸 쇼트헤어"),
    AMERICAN_WIREHAIR("아메리칸 와이어헤어"),
    AMERICAN_CURL("아메리칸 컬"),
    ABYSSINIAN("아비시니안"),
    ORIENTAL_SHORTHAIR("오리엔탈 쇼트헤어 "),
    ORIENTAL_LONGHAIR("오리엔탈 롱헤어 "),
    OCICAT("오시캣 "),
    EUROPEAN("유러피안"),
    EUROPEAN_BURMESE("유러피안버미즈"),
    EGYPTIAN_MAU("이집션마우"),
    EXOTIC("엑조틱"),
    JAPANESE_BOBTAIL("재패니즈 밥테일"),
    CHOSHI("쵸시"),
    KHAO_MANI("카오마니"),
    COLORPOINT_SHORTHAIR("컬러포인트쇼트헤어"),
    CORNISH_REX("코니시 렉스"),
    KORAT("코랫"),
    KURILIAN_BOBTAIL("쿠리리안 밥테일"),
    CYMRIC("킴릭"),
    TIE("타이"),
    HALF_TURKISH("터키시 반"),
    TURKISH_ANGORA("터키시 앙고라"),
    TONKINESE("통키니즈"),
    TOYGER("토이거"),
    TOY_BOB("토이밥"),
    PERSIAN("페르시안"),
    PIXIE_BOB("픽시 밥"),
    PETERBALD("피터볼드"),
    HAVANA_BROWN("하바나브라운"),
    HIMALAYAN("히말라얀");
    private String value;
}


