server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  profiles: dev-1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  redis:
    host: 52.79.162.235
    port: 6379

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      '[hibernate.default_batch_fetch_size]': 100

logging:
  file:
    name: /home/ec2-user/molly/out.log
  level:
    '[kr.co.kumoh.illdang100.mollyspring]': DEBUG